apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  spec:
    project: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    source:
      repoURL: "https://github.com/rakeshparkiti/k8s.git"
      targetRevision: main
      path: "apps/guestbook/guestbook-chart"
    destination:
      name: in-cluster
      namespace: guestbook
