apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-namespace-quota
  namespace: nginx
spec:
  hard:
    requests.cpu: "4" # Total CPU requests limit
    requests.memory: "8Gi" # Total memory requests limit
    limits.cpu: "8" # Total CPU limits
    limits.memory: "16Gi" # Total memory limits
    persistentvolumeclaims: "10" # Maximum number of persistent volume claims
    pods: "20" # Maximum number of pods
    services: "10" # Maximum number of services
    secrets: "" # Maximum number of secrets
    configmaps: "" # Maximum number of configMaps
    replicationcontrollers: "" # Maximum number of replicationcontrollers
    deployments.apps: "" # Maximum number of deployment apps
    replicasets.apps: "" # Maximum number of replicasets
    statefulsets.apps: "" # Maximum number of statefulsets apps
    jobs.batch: "" # Maximum number of jobs
    cronjobs.batch: "" # Maximum number of cronjobs

