apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-master-app
  namespace: argocd
  labels:
    name: nginx-master-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: apps/nginx/applicationset
    repoURL: "https://github.com/rakeshparkiti/k8s.git"
    targetRevision: "main"
  destination:
    namespace: argocd
    server: in-cluster